<a href="https://colab.research.google.com/github/stakunlena/ich_python_for_DA_HW/blob/main/Stakun_HW_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Домашняя работа №2**

**1.  Индексация массивов NumPy:**

Напишите программу, которая:
1.   Запрашивает у пользователя ввод одномерного массива, элементы которого вводятся в виде чисел, разделенных пробелами.
1.   Преобразует введенную строку в массив NumPy.
1.   Запрашивает у пользователя индекс элемента, который необходимо извлечь из массива.
1.   Запрашивает у пользователя ввод диапазона индексов в формате `начало:конец`, чтобы извлечь срез массива.
1.   Выводит срез массива.

In [ ]:
import numpy as np

user_input = input("Введите массив(целые числа, разделённые пробелами): ")

#Преобразуем каждый элемент в целое число
number_list = [int(x) for x in user_input.split()]

arr = np.array(number_list)

index = int(input("Введите индекс элемента: "))

if 0 <= index < len(arr):
    print("Элемент с индексом", index, ":", arr[index])
else:
    print("Ошибка: индекс вне диапазона массива.")

range_input = input("Введите диапазон индексов (начало: конец): ")

#Разделим строки по символу ":"
try:
    start_str, end_str = range_input.split(":")
    start = int(start_str.strip())
    end = int(end_str.strip())

# Получаем и выводим срез
    slice_arr = arr[start:end]
    print("Срез массива:", slice_arr)

except ValueError:
    print("Ошибка: неверный формат диапазона. Используйте формат начало:конец")


Введите массив(целые числа, разделённые пробелами): 1 2 3 4 5 6 
Введите индекс элемента: 2
Элемент с индексом 2 : 3
Введите диапазон индексов (начало: конец): 1:4
Срез массива: [2 3 4]


**2. Операции с матрицами в NumPy**


Напишите программу, которая:

1. Запрашивает у пользователя размеры матрицы MxN.
1. Генерирует две матрицы указанных размеров, заполненные случайными числами от 0 до 9.
1. Выводит обе сгенерированные матрицы на экран.
1. Выполняет и выводит результат одной из следующих операций (на выбор пользователя): сложение матриц, умножение матриц, транспонирование одной из матриц.
1. Если выбрано умножение, убедитесь, что размеры матриц соответствуют правилам матричного умножения.

In [ ]:
import numpy as np

size_input = input("Введите размеры матрицы MxN (например, 2x3): ")
m, n = map(int, size_input.lower().split('x'))

matrix1 = np.random.randint(0, 10, (m, n))
matrix2 = np.random.randint(0, 10, (m, n))

print("\nПервая матрица:")
print(matrix1)

print("\nВторая матрица:")
print(matrix2)

while True:
    print("\nВыберите операцию:")
    print("1 — сложение")
    print("2 — умножение")
    print("3 — транспонирование")

    operation = input("Введите номер операции (1, 2 или 3): ")

    if operation == "1":
        result = matrix1 + matrix2
        print("\nРезультат сложения:")
        print(result)

    elif operation == "2":
        if matrix1.shape[1] == matrix2.shape[0]:
            result = np.dot(matrix1, matrix2)
            print("\nРезультат умножения:")
            print(result)
        else:
            print("\nОшибка: количество столбцов первой матрицы должно быть равно количеству строк второй.")

    elif operation == "3":
        which = input("Какую матрицу транспонировать? (1 или 2): ")
        if which == "1":
            print("\nТранспонированная первая матрица:")
            print(matrix1.T)
        elif which == "2":
            print("\nТранспонированная вторая матрица:")
            print(matrix2.T)
        else:
            print("\nОшибка: нужно ввести 1 или 2.")
    else:
        print("\nОшибка: выбрана неверная операция.")

    again = input("\nХотите выполнить другую операцию? (да/нет): ").lower()
    if again != "да":
        print("\nПрограмма завершена.")
        break


Введите размеры матрицы MxN (например, 2x3): 2x3

Первая матрица:
[[2 9 6]
 [9 1 4]]

Вторая матрица:
[[2 5 2]
 [3 6 1]]

Выберите операцию:
1 — сложение
2 — умножение
3 — транспонирование
Введите номер операции (1, 2 или 3): 1

Результат сложения:
[[ 4 14  8]
 [12  7  5]]

Хотите выполнить другую операцию? (да/нет): да

Выберите операцию:
1 — сложение
2 — умножение
3 — транспонирование
Введите номер операции (1, 2 или 3): 2

Ошибка: количество столбцов первой матрицы должно быть равно количеству строк второй.

Хотите выполнить другую операцию? (да/нет): да

Выберите операцию:
1 — сложение
2 — умножение
3 — транспонирование
Введите номер операции (1, 2 или 3): 3
Какую матрицу транспонировать? (1 или 2): 2

Транспонированная вторая матрица:
[[2 3]
 [5 6]
 [2 1]]

Хотите выполнить другую операцию? (да/нет): нет

Программа завершена.
