<a href="https://colab.research.google.com/github/stakunlena/ich_python_for_DA_HW/blob/main/Stakun_HW_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Домашняя работа №3**

**1.  Сравнение производительности операций над массивами:**

Напишите программу, которая:
1.   Генерирует два больших одномерных массива с 1 миллионом элементов каждый, заполненных случайными числами.
1.   Сначала выполняет поэлементное сложение этих массивов, используя циклы Python.
1.   Затем выполняет ту же операцию, используя возможности NumPy
1.   Измеряет и выводит время выполнения каждого подхода.

In [ ]:
import random
import time
import numpy as np

n = 1_000_000      # размер массивов (1 миллион элементов)
low = 0            # минимальное и максимальное значение для случайного числа
high = 100

# Генерируем два списка с числами

a_np = np.random.randint(low, high, size=n, dtype=np.int64)
b_np = np.random.randint(low, high, size=n, dtype=np.int64)

# 1. Поэлементное сложение в Python (через цикл)

start = time.perf_counter()  # включаем таймер
c_python = []                # сложение результат
for i in range(n):
    c_python.append(a[i] + b[i])  # поэлементно складываем i-е элементы
end = time.perf_counter()         # останавливаем таймер
time_python = end - start         # сохраняем, сколько заняло времени


# 2. Поэлементное сложение в  NumPy

# преобразуем списки в массивы NumPy.
a_list = a_np.tolist()
b_list = b_np.tolist()

start = time.perf_counter()  # включаем таймер
c_numpy = a_np + b_np        # сложение в  NumPy
end = time.perf_counter()    # останавливаем таймер
time_numpy = end - start     # сохраняем время


print(f"Время выполнения сложения с использованием цикла Python: {time_python:.3f} секунды.")
print(f"Время выполнения сложения с использованием NumPy: {time_numpy:.3f} секунды.")


Время выполнения сложения с использованием цикла Python: 0.334 секунды.
Время выполнения сложения с использованием NumPy: 0.004 секунды.


**2. Анализ расположения данных в памяти:**

Создать большой двумерный массив и исследовать, как изменение порядка (C-style и Fortran-style) влияет на производительность операций сложения и умножения.

Можно использовать тот же бенчмарк что и в лекции. Необходимо погуглить про то, как завести массив с порядком в Fortran-style. Не забывайте про magic в jupyter.

In [ ]:
# Импортируем библиотеки
import numpy as np
import time

# Устанавливаем размер массива (6000 строк, 1000 столбцов)
rows = 6000
cols = 1000

# Создаём два массива случайных чисел от 0 до 1 в C-порядке (по строкам)
array_c1 = np.random.rand(rows, cols)
array_c2 = np.random.rand(rows, cols)

# Создаём массивы с теми же данными, но в Fortran-порядке (по столбцам)
array_f1 = np.array(array_c1, order='F')
array_f2 = np.array(array_c2, order='F')

# Проверяем порядок хранения данных в памяти
print("C-order flags:    array_c1:", array_c1.flags['C_CONTIGUOUS'], "F:", array_c1.flags['F_CONTIGUOUS'])
print("Fortran-order flags: array_f1:", array_f1.flags['C_CONTIGUOUS'], "F:", array_f1.flags['F_CONTIGUOUS'])
print("Shapes:", array_c1.shape, array_c2.shape, array_f1.shape, array_f2.shape)

# Измеряем время поэлементного сложения массивов
print("\nElement-wise addition timings:")

# Сложение C-порядка
get_ipython().run_line_magic('timeit', 'array_c1 + array_c2')

# Сложение Fortran-порядка
get_ipython().run_line_magic('timeit', 'array_f1 + array_f2')

# Измеряем время поэлементного умножения массивов
print("\nElement-wise multiplication timings:")

# Умножение C-порядка
get_ipython().run_line_magic('timeit', 'array_c1 * array_c2')

# Умножение Fortran-порядка
get_ipython().run_line_magic('timeit', 'array_f1 * array_f2')


C-order flags:    array_c1: True F: False
Fortran-order flags: array_f1: False F: True
Shapes: (6000, 1000) (6000, 1000) (6000, 1000) (6000, 1000)

Element-wise addition timings:
19 ms ± 889 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
19.4 ms ± 1.17 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

Element-wise multiplication timings:
19.2 ms ± 945 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
21.8 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


**1. Обратная матрица и определитель:**

Напишите программу, которая:
1. Запрашивает у пользователя размер квадратной матрицы N.
1. Генерирует квадратную матрицу размером N x N, заполненную случайными числами от -10 до 10.
1. Выводит сгенерированную матрицу на экран.
1. Вычисляет и выводит определитель матрицы.
1. Если определитель не равен нулю, программа должна вычислить и вывести обратную матрицу. В противном случае, программа должна сообщить, что обратной матрицы не существует.

In [ ]:
import numpy as np
try:
    N = int(input("Введите размер матрицы N: "))

    if N <= 0:
        print("Размер матрицы должен быть положительным числом.")
    else:
        # Генерируем матрицу NxN со случайными целыми числами от -10 до 10
        matrix = np.random.randint(-10, 11, size=(N, N))

        print("\nСгенерированная матрица:")
        print(matrix)

        try:
            # Вычисляем определитель
            determinant = np.linalg.det(matrix)
            print("\nОпределитель матрицы:", round(determinant, 2))

            # Проверяем, существует ли обратная матрица
            if determinant != 0:
                inverse_matrix = np.linalg.inv(matrix)

                print("\nОбратная матрица:")
                print(np.round(inverse_matrix, 2))  # округляем до 2 знаков
            else:
                print("\nОбратной матрицы не существует (определитель равен 0).")

        except np.linalg.LinAlgError:
           print("\nОшибка при вычислении обратной матрицы.")

except ValueError:
    # Обработка ошибки, если пользователь ввёл не число
    print("Ошибка: введите целое число.")


Введите размер матрицы N: 3

Сгенерированная матрица:
[[ 1  4 -1]
 [-3  6 -2]
 [ 5  0 -4]]

Определитель матрицы: -82.0

Обратная матрица:
[[ 0.29 -0.2   0.02]
 [ 0.27 -0.01 -0.06]
 [ 0.37 -0.24 -0.22]]
